### ISSUE TITLE
Charade Dataset

### ISSUE THREAD

**Issue by frostinassiky** [ChenJoya/2dtan#1]
Dear Joya,

Thanks for sharing the optimized code! The improvements on Charade and ActivityNet Datasets are impressive!

Do you have any plan to support Charade dataset?

**Comment by ChenJoya** [comment]
Dear Frostinassiky,

Thanks for your attention for this repo! The feature of Charades-STA is hard to download as it is too large in Google Cloud (16G) 😂... We will try to download it and give the result of it. Thank you!

**Comment by frostinassiky** [comment]
I see 😂 Do you use the same feature as in the official 2D-TAN? 

Your code is very well-organized! I can try to do this experiment and (maybe) pull to the repo.

**Comment by ChenJoya** [comment]
Yeah, I use the same feature.
Thanks for your praise! Could I have your wechat and communicate with you about this field?

**Comment by MinamiKotoka** [comment]
> Dear Joya,
> 
> Thanks for sharing the optimized code! The improvements on Charade and ActivityNet Datasets are impressive!
> 
> Do you have any plan to support Charade dataset?

Hi, I also test in Charades dataset, but do not have a prominet improvement. Could you share your result on Charades? Thank you.

**Comment by frostinassiky** [comment]
@MinamiKotoka Are you able to reproduce the 2DTAN paper results from this repo?

**Comment by jun0wanan** [comment]
> @MinamiKotoka Are you able to reproduce the 2DTAN paper results from this repo?

hi,have you reproduce ?~

**Comment by frostinassiky** [comment]
No, I haven't
