### ISSUE TITLE
ActivityNet feature corrupt?

### ISSUE THREAD

**Issue by wjn922** [ChenJoya/2dtan#8]
Hi,

    Thanks for your great work and code. 
    The ActivityNet feature seems to be corrupted. I tried several times and it always has this problem. Could you please help? Or could you provide the link for downloading sub_activitynet_v1-3.c3d.hdf5? Thanks.
![image](https://user-images.githubusercontent.com/21001460/115991142-c1b16400-a5f9-11eb-9c5a-ee9756c2b1ae.png)

**Comment by jun0wanan** [comment]
> Hi,
> Thanks for your great work and code.
> The ActivityNet feature seems to be corrupted. I tried several times and it always has this problem. Could you please help? Or could you provide the link for downloading sub_activitynet_v1-3.c3d.hdf5? Thanks.
> ![image](https://user-images.githubusercontent.com/21001460/115991142-c1b16400-a5f9-11eb-9c5a-ee9756c2b1ae.png)

can you tell me how to solve it ?

**Comment by ChenJoya** [comment]
The CRC error is most likely to occur when the network is interrupted and download again. Maybe you can download it again, with some strict downloading restriction.

**Comment by jun0wanan** [comment]
> 当网络中断并重新下载时，最有可能发生CRC错误。也许您可以再次下载它，但有一些严

> The CRC error is most likely to occur when the network is interrupted and download again. Maybe you can download it again, with some strict downloading restriction.

Do you mind share us ? ╥﹏╥..., I have download 4 times
